### ISSUE TITLE
train_rnn

### ISSUE THREAD

**Issue by Crescentz** [yu45020/Pytorch_Learning_Note#1]
请问train_rnn 里的sample.json是哪个呀  ，这个工程的脉络文件。。
我特换成了poetry_idx发现提示object of type 'int' has no len()

poetry_data = './data/sample.json'

Traceback (most recent call last):
  File "E:/CODE/practice/Pytorch_Learning_Note-master/Pytorch_Learning_Note-master/Negative Sampling and LSTM/train_rnn.py", line 36, in <module>
    train_data = prepare_data_loader(train,max_topic_len, max_length, batch_size, shuffle=True)
  File "E:\CODE\practice\Pytorch_Learning_Note-master\Pytorch_Learning_Note-master\Negative Sampling and LSTM\model_rnn.py", line 70, in prepare_data_loader
    dataset = PoetryRNNData(data, max_topic_counts=max_topic_len, max_poetry_length=max_length)
  File "E:\CODE\practice\Pytorch_Learning_Note-master\Pytorch_Learning_Note-master\Negative Sampling and LSTM\model_rnn.py", line 32, in __init__
    self.topic_lens = torch.LongTensor([min(len(x), max_topic_counts) for x in topics])
  File "E:\CODE\practice\Pytorch_Learning_Note-master\Pytorch_Learning_Note-master\Negative Sampling and LSTM\model_rnn.py", line 32, in <listcomp>
    self.topic_lens = torch.LongTensor([min(len(x), max_topic_counts) for x in topics])
TypeError: object of type 'int' has no len()

**Comment by yu45020** [comment]
[数据来源](https://github.com/chinese-poetry/chinese-poetry)， 我只用了一部分。

**Comment by Crescentz** [comment]
不是这个意思，此数据文件我找到了。
问题没清楚：在你的tran_rnn.py文件中，数据来源是sample.json，根据你的描述，应该是poetry_idx.json文件，可是当尝试替换成这个文件的时候，会出现上述问题，int 没有len()。
poetry_idx.json是个二维二元的数组，只包换诗的idx

**Comment by yu45020** [comment]
原文档随服务器一起删除了， json文档都没有。 
输入的数据应该是
```python
[  [[关键词]，[诗句]], [[关键词]，[诗句]], ...]
```
poetry_idx的内容要先经过关键词提取，可参考[这](https://github.com/yu45020/Pytorch_Learning_Note/blob/b4b89b604fc2effd1ac16359f842b2f143019309/Negative%20Sampling%20and%20LSTM/model_rnn.py#L30)

**Comment by Crescentz** [comment]
谢谢指点，，，彻底放弃了，看了几天，没找到那个文件是how to w出来的，谢谢解答

**Comment by yu45020** [comment]
或许还可以参考pytorch的[教程](https://pytorch.org/tutorials/beginner/chatbot_tutorial.html). 关注点其实都在模型的设计上，其他比如数据处理，输入的步骤都是按需写的。 别急，慢慢来。
